language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install coveralls unittest2
env:
  - SOLR_VERSION=4.6.1 SOLR_URL=http://localhost:8983/solr/collection1 SOLR_CONFS="scorched/tests/solrconfig.xml"
# command to run tests
before_script: curl https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | bash
script: nosetests -s scorched
after_script: killall java
after_success:
    coveralls --verbose
