language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install -e .[test]
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
env:
  - SOLR_VERSION=4.10.2 SOLR_URL=http://localhost:8983/solr/core0 SOLR_CONFS="scorched/tests/solrconfig.xml"
# command to run tests
# before_script: curl https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | bash
before_script: ./testing-solr.sh
script: nosetests -s scorched
after_script: killall java
after_success:
    coveralls --verbose
